# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.gz

# --- CONFIGURACIÓN DE RED Y AUTENTICACIÓN ---
listener 1883
allow_anonymous false
# Esta ruta es interna del contenedor, no la cambies
password_file /mosquitto/config/passwd

# --- PERSISTENCIA Y LOGS ---
persistence true
# Esta ruta es interna del contenedor
persistence_location /mosquitto/data/

# Esta ruta es interna del contenedor
log_dest file /mosquitto/log/mosquitto.log
