version: '3.3'
services:
  influxdb3-core:
    container_name: influxdb3-core
    image: influxdb:3-core
    user: "0:0"
    ports:
      - 8181:8181
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
      - --without-auth
    volumes:
      - influxdb3_data:/var/lib/influxdb3/data
      - influxdb3_plugins:/var/lib/influxdb3/plugins
    networks:
      - alarma_network

  mosquitto:
    container_name: mosquitto_broker
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./passwd:/mosquitto/config/passwd:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./npm_letsencrypt:/etc/letsencrypt:ro
    networks:
      - alarma_network

  telegraf:
    container_name: telegraf_agent
    image: telegraf:latest
    restart: always
    depends_on:
      - influxdb3-core
      - mosquitto
    environment:
      - INFLUX_BUCKET=sensores_db
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - alarma_network

  nodered:
    container_name: nodered
    image: nodered/node-red
    ports:
      - 1880:1880
    depends_on:
      - influxdb3-core
      - mosquitto
    volumes:
      - ./nodered_data:/data
    networks:
      - alarma_network
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt
    networks:
      - alarma_network

volumes:
  influxdb3_data:
  influxdb3_plugins:
  mosquitto_data:
  mosquitto_log:

networks:
  alarma_network:
    name: alarma_network
