[agent]
  interval = "2s"                # Frecuencia de recolección general
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  flush_interval = "2s"          # Envío rápido a InfluxDB cada 2 segundos
  flush_jitter = "0s"
  precision = "1ms"

# -- SALIDA A INFLUXDB V3 CORE --
[[outputs.influxdb_v2]]
  # Usamos el nombre del servicio de docker y el puerto 8181
  urls = ["http://influxdb3-core:8181"] 
  token = "$INFLUX_TOKEN"
  organization = "default"       # InfluxDB v3 Core suele ignorar la org, pero se requiere el parámetro
  bucket = "$INFLUX_BUCKET"

# -- ENTRADA DESDE MOSQUITTO LOCAL --
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = [
    "alarma/estado",
    "alarma/comando",
    "alarma/acel",
    "alarma/evento"
  ]
  
  # --- AGREGA TUS CREDENCIALES AQUÍ ---
  username = "claromio"
  password = "RiverBest"
  
  data_format = "json"
  json_string_fields = ["estado", "modo"]
  name_override = "datos_sensores"
